from glob import glob

print("//! Metadata files")
print("//!")
print("//! DO NOT EDIT MANUALLY")
print("//! generated by: python3 generate-meta-db.py > library/src/meta.rs")


def generate_version(version):
    folder = "./polyfill-libraries/" + version
    files = glob(folder + "/*/meta.json")
    safe_version = version.replace(".", "_")

    def key(name):
        return f"F_{safe_version}_" + name \
            .replace("/", "_") \
            .replace(".", "_") \
            .replace("-", "_") \
            .replace("~", "_") \
            .replace("@", "_") \
            .upper()

    for file in files:
        f = open(file, "r")
        contents = f.read()
        f.close()

        name = key(file.replace(folder, ""))

        print("const %s: &str = r#\"%s\"#;" % (name, contents))

    print("")
    print("pub(crate) fn lookup_" + safe_version + "(n: &str) -> Option<&'static str> {")
    print("  match n {")

    for file in files:
        name = file.replace(folder, "")
        print("    \"%s\" => Some(%s)," % (name, key(name)))

    print("    _ => None,")
    print("  }")
    print("}")


generate_version("3.111.0")
